### ISSUE TITLE
bro stop spamming panels 

### ISSUE THREAD

**Issue by gabjohn3** [OwenKruse/OwenKruse.github.io#2]
Hey bro go and get ur own bots
Stop spamming ur sht on panels is annoying have to delete ur chatgpt xss xd

**Comment by gabjohn3** [comment]
Bro pls stop spamming ur chatgpt xss it doesnt work its annoying deleting ur pathetic xss from panels LOL

**Comment by OwenKruse** [comment]
I stopped a long time ago. Everything is just a copycat now. Lots of them too lol
